### ISSUE TITLE
Next Steps section

### ISSUE THREAD

**Issue by rukshang82** [AdobeDocs/experience-manager-64.en#1]
The "Next Steps" URL's requires you to be on the Adobe Corp network. This does not help who are not with Adobe

**Comment by ashishguptaiitb** [comment]
Hi @rukshang82 , thanks for sharing. Could you also please share the page that you encountered this issue on? We shall address it.

**Comment by rukshang82** [comment]
https://docs.adobe.com/content/help/en/experience-manager-64/forms/install-aem-forms/jee-installation/installing-and-configuring-the-document-security-server.html

At the very bottom "Next Steps" section

Thanks
Ruk

**Comment by ashishguptaiitb** [comment]
Thanks @rukshang82 , appreciate the pointer. I've shared it internally for an update.

**Comment by anujkapo** [comment]
Hi @rukshang82, the dead links, in the 'Next Steps' section at the end, have been fixed now. Thanks! 

Thanks @ashishguptaiitb for the follow-up.
