### ISSUE TITLE
"Text.replace"-Method leads to "Java heap space" Error

### ISSUE THREAD

**Issue by esodot** [AdobeDocs/experience-manager-64.en#100]
**Jar:** com.adobe.aem:uber-jar:apis:6.4.3
**Class:** com.day.text
**Method:** public static String replace(String text, String oldString, String newString);

Can produce _java.lang.OutOfMemoryError: Java heap space_ if passing Empty-String as oldString-Parameter.

**Test-Case:**
Text.replace("/content/mycontent/com/jobs", "", "/content/mycontent/com");

`java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuffer.append(StringBuffer.java:270)
	at com.day.text.Text.replace(Text.java:242)`

**Comment by aheim0** [comment]
@esodot Thank you for highlighting this, though it is not a matter for the documentation. We will however, pass your comment on to the Engineering team.

**Comment by aheim0** [comment]
Tracking with CQ-4300168.

**Comment by aheim0** [comment]
Closing as this issue is now outside our jurisdiction.

**Comment by esodot** [comment]
hi @aheim0 where exactly can i track the progress of the issue you forwarded to Engineering team? Thank you

**Comment by aheim0** [comment]
@esodot That is for our internal tracking only. For anything more we would have to suggest you open a Support ticket.
