### ISSUE TITLE
Compatibity package link is broken

### ISSUE THREAD

**Issue by manish112** [AdobeDocs/experience-manager-64.en#101]
Issue in help/sites-deploying/backward-compatibility.md

The compatibility package link still points to https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq640/compatpack/aem-compat-cq64-to-cq63

while the new link is https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/cq640/compatpack/aem-compat-cq64-to-cq63

**Comment by aheim0** [comment]
@manish112 Thanks for highlighting this, we will investigate.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16466.

**Comment by aheim0** [comment]
The link has been fixed. Thanks for the information.
