### ISSUE TITLE
json.maximumresults default is actually 1000, not 200

### ISSUE THREAD

**Issue by somarc** [AdobeDocs/experience-manager-64.en#103]
Issue in help/sites-administering/security-checklist.md

JSON Max results ( json.maximumresults )
in the configuration for the Apache Sling GET Servlet . When this limit is exceeded the rendering will be collapsed. The default value for Sling within AEM is 200 .

The default is actually 1000. 200 is incorrect.

**Comment by anujkapo** [comment]
Thanks, @somarc for reporting the issue. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16489.

**Comment by aheim0** [comment]
Thanks for highlighting this. The value has been updated for both 6.4 and 6.5.
Closing this issue now.
