### ISSUE TITLE
Copy the CLient ID to  enter in the API key field

### ISSUE THREAD

**Issue by Vishawdhaliwal** [AdobeDocs/experience-manager-64.en#104]
Issue in help/assets/config-smart-tagging.md

Please update the doc with below info:
- Copy the Client ID from the Service Account (JWT) and paste it in the API key in Cloud config in AEM.

**Comment by anujkapo** [comment]
Thanks, @Vishawdhaliwal. We will add the information to the article.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16553.

**Comment by mgulati1** [comment]
Thanks @Vishawdhaliwal. Fixed the issue. Creating a ticket to update the 6.5 documentation too.
