### ISSUE TITLE
Annotate component requires special configuration

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-64.en#105]
Issue in help/sites-authoring/annotations.md

Need to add the following note to the documentation:

To enable the annotation feature at the component level, you need to set cq:editConfig/@cq:actions to include "editannotate" instead of "edit".

**Comment by anujkapo** [comment]
Thanks, @jbrarAdobe for the suggestion. We will look into it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16565.

**Comment by bohnertchris** [comment]
@jbrarAdobe what led you to this conclusion? If I look at the Core Components, they don't seem to have this property, yet I can annotate them in the authoring interface. Can you provide an example?

**Comment by jbrarAdobe** [comment]
Hi Chris,

This issue was logged around 6 months ago and the core component release at that time seemed to have this issue.
I believe it's now fixed in the latest core components release.

**Comment by bohnertchris** [comment]
Thanks for the feedback, @jbrarAdobe. Sorry for the long delay in addressing this issue.
