### ISSUE TITLE
Compatibility Matrix for FileNet versions missing.

### ISSUE THREAD

**Issue by shimlite** [AdobeDocs/experience-manager-64.en#106]
Issue in help/forms/using/admin-help/configuring-connector-ibm-filenet.md

Can you please add the compatibility matrix for different FileNet versions.

Is the AEM version 6.4 compatible with FileNet version 5.5.5 ?

**Comment by bohnertchris** [comment]
Thank you for the issue, @shimlite. We will review.

CQDOC-16620

**Comment by anujkapo** [comment]
@shimlite, the compatibility matrix for IBM Filenet is available in the 6.4 and 6.5 docs at:

- https://docs.adobe.com/content/help/en/experience-manager-65/forms/install-aem-forms/jee-installation/aem-forms-jee-supported-platforms.html#Contentmanagersandcorrespondingconnectors
- https://docs.adobe.com/content/help/en/experience-manager-64/forms/install-aem-forms/jee-installation/aem-forms-jee-supported-platforms.html#Contentmanagersandcorrespondingconnectors

6.4 version supports IBM Filenet version 5.2. 6.5 supports IBM Filenet versions 5.2 and 5.5.2
