### ISSUE TITLE
different number is mentioned in another page

### ISSUE THREAD

**Issue by anusss201** [AdobeDocs/experience-manager-64.en#107]
Issue in help/assets/smart-tags-training-guidelines.md

In the below link it is mentioned that we need minimum 10 images for training smart tags. But in the above link it mentions minimum 30 images. which options is correct do we need minimum 10 training images are 30 training images to train the smart tags.

https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/manage/smart-tags.html

Thanks

**Comment by mgulati1** [comment]
@anusss201 Thanks for the suggestion. We will look into it.

**Comment by ashishguptaiitb** [comment]
Hi @anusss201 , AEM introduced AI/ML-based smart tagging in AEM 6.4. This year, AEM introduced AEM as a Cloud Service. Previously, in AEM 6.4, it required 30 images to train the tagging model. The algorithms have become better (and faster) now. The latest AEM offering only needs 10 images to train the model.

The article you logged the ticket on and the linked article, both apply to different AEM versions and hence the difference. If it helps to know, the URL of a help article indicates the AEM version that it applies to.

Do let me know if there's anything we can do to improve the articles or if I understood your concern incorrectly. Thank you.

**Comment by bohnertchris** [comment]
CQDOC-16621

**Comment by ashishguptaiitb** [comment]
Hi @anusss201 , have you had a chance to look at the docs that are specific to your AEM version? Is there anything that we can help improve? If there's nothing, I'd like to close this issue.

**Comment by anusss201** [comment]
I am good now. In my case it would be 30.

Thanks,
