### ISSUE TITLE
Tag IDs not updating on page items after being moved under new container tag parent

### ISSUE THREAD

**Issue by siidny** [AdobeDocs/experience-manager-64.en#112]
Issue in help/sites-developing/building.md

When tags are moved in the Tag Manager, the respective tags on page items (displayed in header metadata) are not being updated.
 
So if it is decided that a Container tag needs to be moved under a new parent container tag, the tag path changes.
 
However, I’ve noticed that after doing this the tag on the page item retains the old tag path.
 
I’m hoping to find out if AEM is supposed to adjust the tag reference paths on the page properties, or is that a manual process?

**Comment by aheim0** [comment]
Thank you for contacting us, but unfortunately this is out of scope for the documentation.

Can we please ask you to contact your support representative for such questions. Thanks in advance.
