### ISSUE TITLE
Compiled JSP files are no more  in /var/classes location

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-64.en#113]
Issue in help/sites-developing/the-basics.md

In the section "Structure within the Repository", the statement "The sub-folder **/var/classes** contains the java servlets in source and compiled forms that have been generated from the components scripts." is not true anymore.

 Since AEM 6.1, compiled JSP files are no more  in /var/classes location.

**Comment by anujkapo** [comment]
Thanks, @vdhaliwa. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16803.

**Comment by bohnertchris** [comment]
This has been corrected in commit fc09607 to the 6.4 repo and in commit 8be4e41 to the 6.5 repo.
