### ISSUE TITLE
Assets CC Integration refers to legacy oauth

### ISSUE THREAD

**Issue by godanny86** [AdobeDocs/experience-manager-64.en#114]
Issue in help/sites-administering/configure-assets-cc-integration.md

The document refers to https://legacy-oauth.cloud.adobe.io/ which cannot be reached...

**Comment by anujkapo** [comment]
Thanks, @godanny86. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16834.

**Comment by ashishguptaiitb** [comment]
The configuration does not exist. I've removed the integration articles from the docs. RNs are updated with the relevant info. Redirects will be established soon. Closing this issue. 

FYI, a related ticket was https://github.com/AdobeDocs/experience-manager-65.en/issues/230
