### ISSUE TITLE
6.5 version of this page does not exist

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-64.en#116]
Issue in help/assets/gql-search.md

https://docs.adobe.com/content/help/en/experience-manager-64/assets/using/gql-search.html

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17024.

**Comment by ashishguptaiitb** [comment]
Hi @lha-adobe , please see https://docs.adobe.com/help/en/experience-manager-65/assets/using/search-assets.html#gqlsearch

**Comment by ashishguptaiitb** [comment]
Hi @lha-adobe , does this content work for you? Do you have any suggestions to improve?

**Comment by lha-adobe** [comment]
@ashishguptaiitb  this looks good.  I typically refer customer to documentation on the same product version and this one just looked to be missing.

**Comment by ashishguptaiitb** [comment]
Thanks for the diligence @lha-adobe . Appreciate it.
