### ISSUE TITLE
No method of validating user CFM input

### ISSUE THREAD

**Issue by FL33TW00D** [AdobeDocs/experience-manager-64.en#117]
Issue in help/sites-developing/customizing-content-fragments.md

Currently there is no method in the AEM documentation describing how to validate the user input at the CFM authoring stage. The only lead is on the forums here: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/how-to-provide-validation-s-existing-content-fragment-models/qaq-p/286329

And that specifies editing/adding files to the /libs/ folder, which is against all recommendations from the AEM docs.

**Comment by bohnertchris** [comment]
Thank you for brining this up, @FL33TW00D. We will investigate.

CQDOC-17052

**Comment by FL33TW00D** [comment]
@bohnertchris Thanks for coming back so quickly let me know if you have a resolution.

**Comment by bohnertchris** [comment]
@FL33TW00D we will of course update this issue as we make changes to the documentation. Please note however that this repository is to report  issues with the documentation only. If you require technical assistance for AEM, please use the Experience Cloud Enterprise Support portal [1] to contact our AEM Customer Care team.

https://helpx.adobe.com/contact/enterprise-support.ec.html

**Comment by aheim0** [comment]
We have opened a separate issue for the communities article to be updated, in line with best practices and recommendations.
Tracked with COMM-1042.
