### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by gyantalwar** [AdobeDocs/experience-manager-64.en#121]
Issue in ./help/sites-developing/hobbes.md

Third sentence in the document requires a space between a and javascript:

"The framework provides **ajavascript** API for creating tests."

**Comment by anujkapo** [comment]
Thanks, @gyantalwar. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-17213.

**Comment by aheim0** [comment]
The typo has been fixed and the page published (might take a while to appear).
Closing this.
