### ISSUE TITLE
the Screenshot too small and instructions unclear

### ISSUE THREAD

**Issue by jasmeet2dhiman** [AdobeDocs/experience-manager-64.en#122]
on this page https://experienceleague.adobe.com/docs/experience-manager-64/assets/administer/indesign.html?lang=en#how-the-extraction-works

under this is section

Configuring Day CQ Link Externalizer

the Screenshot too small and the instructions unclear.

can we please provide information on what needs to be done?

**Comment by ashishguptaiitb** [comment]
Agreed @jasmeet2dhiman that "_Specify the host name and context path for the Indesign server_" are not the most helpful. Allow us some time to update this.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17280.

**Comment by ashishguptaiitb** [comment]
Hi @jasmeet2dhiman please see https://experienceleague.adobe.com/docs/experience-manager-64/assets/administer/indesign.html#configuring-day-cq-link-externalizer . I've added a screenshot that's more readable. Also, see description of each field in the screenshot/on UI. Hope it helps.

**Comment by ashishguptaiitb** [comment]
Hi @jasmeet2dhiman , I hope the updates helped you. If more info is required, let us know.
