### ISSUE TITLE
Classic UI screenshots in AEM Assets documentation for AEM 6.4

### ISSUE THREAD

**Issue by ichirital** [AdobeDocs/experience-manager-64.en#125]
Issue in ./help/assets/assets.md

https://experienceleague.adobe.com/docs/experience-manager-64/assets/assets.html?lang=en#what-is-digital-asset-management

Improvement: Suggest to replace existing Classic UI screenshots with Touch UI to avoid promoting or implying Classic UI is the preferred interface for managing Assets in AEM.

**Comment by anujkapo** [comment]
Thanks, @ichirital. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-17416.

**Comment by ashishguptaiitb** [comment]
Thanks @ichirital for sharing this. Agree that we don't want to highlight Classic UI. Those screenshots were not much of a value add so I've removed those. I've added a link to the official video intro of Assets that's much more useful.
