### ISSUE TITLE
Several typos

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-64.en#130]
Issue in ./help/sites-administering/content-disposition-filter.md

pfd instead of "PDF"
fo instead of "of"
Probably others

**Comment by anujkapo** [comment]
Thanks, @mattlaun. We will fix them.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17677.

**Comment by bohnertchris** [comment]
These typos have been corrected in 6.4 with commit 770a036 and in 6.5 with commit b20da45.
