### ISSUE TITLE
Software Distribution link does not link properly

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-64.en#131]
Issue in ./help/assets/aem-pdf-rasterizer.md

The Software Distribution link makes you click another button which takes you to experience.adobe.com, which then sends you to the experience league forums instead of software distribution. Link needs to be pointed to the proper destination.

**Comment by thedoc31** [comment]
Turns out it was because I was signed in with my regular user instead of my Enterprise user. The "You don't have access to this" message is not clear enough for me to understand why I can't see what I clicked on. Suggest you improve this workflow to make it abundantly clear what the issue is to avoid confusion.

**Comment by aheim0** [comment]
Although we understand, and sympathize with, your issues, this is not within the scope of the documentation, so we cannot help. 
We suggest that you open a support ticket to pursue the issue with the software distribution team. 
Closing this issue.
