### ISSUE TITLE
Customer report, Generated PDF previews in AEM are not high enough resolution

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-64.en#135]
Issue in [./help/assets/aem-pdf-rasterizer.md](https://experienceleague.adobe.com/docs/experience-manager-64/assets/administer/aem-pdf-rasterizer.html?lang=en)

{quote}
Request is to add further notes for specific scenario for high resolution PDF as defined in Dynamics Ticket: **E-000398675**

 
PDF Rasterizer itself limit the previews to 1280 pixels max, but the “Web Enabled Image” sub-step of the PDF Rasterizer process step, which was enabled and used by default for both the main asset previews and any sub asset previews.
 
By configuring PDF Rasterizer to generate 3,300 pixel JPEG previews for both the main and sub assets and simultaneously disabling the  ‘Web Enabled Image’ and thumbnail sub-steps, customer can force AEM to use the higher-quality preview images -- which means they can be zoomed into much further before the quality deteriorates (at the current settings they are effectively rasterized at 300 pixels-per-inch for an 8.5” x 11” PDF).
 
Customer can also force PDF Rasterizer to use the first page of the PDF as thumbnail! Here are the current settings:

PDFRasterizer -d -s 3300 -p 1 -t JPEG -i ${file}
  
The only potential downside to these larger, higher-quality previews is that they will increase page load times and take up a bit more disk space -- but that’s always the trade-off for increased quality and resolution.
{quote}

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @aaksinghAdobe. The assets documentation team will review this suggestion.
