### ISSUE TITLE
You can't open properties of a folder if you are in that folder

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-64.en#136]
Issue in ./help/assets/image-profiles.md

This sentence is wrong:
"1. Tap the AEM logo and navigate to Assets and then to the folder that you want to apply an image profile to."
when followed by this sentence:
"2. On the folder, tap the check mark to select it and then tap Properties."
because you cannot "tap" a folder when you in that folder.

Sentence should read:
"1. Tap the AEM logo and navigate to Assets and then to the parent folder of the folder that you want to apply an image profile to."

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @johnb4. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by mgulati1** [comment]
Added fix in 6.4, 6.5, and CS versions.
