### ISSUE TITLE
Dead link in documentation page.

### ISSUE THREAD

**Issue by vcohen-irvinecompany** [AdobeDocs/experience-manager-64.en#137]
In the section 
https://experienceleague.adobe.com/docs/experience-manager-64/developing/components/developing-components.html?lang=en#coral-ui-and-granite-ui
there's a paragraph that says:

> For more information on developing components using Coral and Granite resource types see: [Building Experience Manager components using Coral/Granite resource types.](https://helpx.adobe.com/experience-manager/using/aem64_coral_resourcetypes.html)

That link returns a 404.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. Unfortunately the article referenced is no longer maintained/available, so I have removed the link (for both 6.4 and 6.5).
Closing this issue.
