### ISSUE TITLE
Not applicable to sdk installs

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-64.en#160]
Issue in ./help/sites-developing/we-retail.md
This document is apparently not applicable to sdk installs. When I try to install the newly downloaded we-retail package on my sdk install, I'm missing dependencies. 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/98857862/169351563-f76f49cf-59df-42e1-a9aa-cbfe5589339a.png">

**Comment by aheim0** [comment]
Thanks for raising this, but if there are issues with the downloaded package then that is outside our scope.
You can contact support for further help, but we must warn you that normal support for AEM 6.4 has expired:
- https://helpx.adobe.com/support/programs/eol-matrix.html
Hope that helps, closing this issue now.
