### ISSUE TITLE
references to offloading, which was removed in 6.5?

### ISSUE THREAD

**Issue by joshwand** [AdobeDocs/experience-manager-64.en#29]
There are many many references to assets offloading in the docs, but this feature was removed in 6.5 according to [the 6.5 release notes](https://helpx.adobe.com/experience-manager/6-5/release-notes/deprecated-removed-features.html): 
> The Assets Offloading feature has been removed in AEM 6.5

**Comment by ashishguptaiitb** [comment]
Thanks @joshwand  for sharing this. We've removed the offloading information in AEM 6.5 docs. This particular GitHub repo is for AEM 6.4 docs. The 6.4 Assets offloading article includes the appropriate deprecation notice at https://docs.adobe.com/content/help/en/experience-manager-64/assets/administer/assets-offloading-best-practices.html

To explore more 6.4 Assets help, see https://docs.adobe.com/content/help/en/experience-manager-64/assets/home.html

The corresponding article and its references are removed from the 6.5 Assets help offering.

Hope this helps. Let me know if I've missed any instance or update.

**Comment by joshwand** [comment]
References are still present in the 6.5 docs:

* https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/performance-tuning-guidelines.html#offloading
* https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/assets-sizing-guide.html

Furthermore, clicking the "edit this page" or "log an issue" links send me to this experience-manager-64.en repo.

**Comment by ashishguptaiitb** [comment]
Thanks @joshwand for sharing. I shall address these as well and get back next week.

**Comment by ashishguptaiitb** [comment]
Hi @joshwand , I've addressed this in AEM 6.5 docset. Have a look and let me know if I missed anything. If not, I shall close this issue.
Appreciate you sharing this.

**Comment by ashishguptaiitb** [comment]
Hi @joshwand , I'm closing this issue for now. If there's anything more that I can help with, do share.

**Comment by Andrew-Cottrell** [comment]
FYI, this document implies the Assets Offloading feature remains available in AEM 6.5

- Link: https://helpx.adobe.com/uk/experience-manager/6-5/assets/using/assets-offloading-best-practices.html
- Applies to: Experience Manager 6.5 Assets
- Last Published: 20 April 2020

**Comment by Andrew-Cottrell** [comment]
I'm unclear if this is also referring to the Asset Offloading feature that was removed

- Link: https://docs.adobe.com/content/help/en/experience-manager-65/deploying/configuring/offloading.html#offloading-the-processing-of-dam-assets

**Comment by ashishguptaiitb** [comment]
Good catch @Andrew-Cottrell . This is leftover localized content that wasn't removed. I shall get all instances of the article removed. Also, I shall remove the section in the other article. Thanks for sharing.

**Comment by ashishguptaiitb** [comment]
@Andrew-Cottrell , an update that AEM 6.5 articles on docs.adobe.com articles are updated to remove Assets offloading feature. The helpx.adobe.com article will get retired in a few days. I shall update then.

**Comment by ashishguptaiitb** [comment]
Tracking internally via CQDOC-16426

**Comment by ashishguptaiitb** [comment]
Hi @Andrew-Cottrell , now the helpx links are gone as those should have been :) I believe I don't have Assets offloading content in the docs now. I there's anything please let me know. Thanks for this observation. I'm closing this ticket now.

**Comment by riteshmittal** [comment]
Hi @ashishguptaiitb ,

I still see that the AEM 6.5 documentation has reference to Assets offloading-

https://experienceleague.adobe.com/docs/experience-manager-65/deploying/configuring/offloading.html?lang=en

**Comment by ashishguptaiitb** [comment]
Hi @riteshmittal , are you suggesting that this 65 article for offloading should go?
