### ISSUE TITLE
Filevault is not included with AEM 6.4 or 6.5

### ISSUE THREAD

**Issue by cirklone** [AdobeDocs/experience-manager-64.en#33]
Issue in [help/sites-developing/ht-vlttool.md](https://github.com/AdobeDocs/experience-manager-64.en/blob/master/help/sites-developing/ht-vlttool.md)

The documentation page says that Apache Jackrabbit Filevault is included with AEM in `./crx-quickstart/opt/helpers/`. The last version it was included was AEM 6.3.

The latest version of Apache Jackrabbit Filevault may be downloaded at https://jackrabbit.apache.org/jcr/downloads.html#vlt

The version recommend to download from Adobe PackageShare is version 2.4 even though the version described on the page as an example is version 3.1. The current version today is 3.4 and will require Java 8 or greater. It might make sense to point folks to the Github site where the source code lives at https://github.com/apache/jackrabbit-filevault.

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @cirklone. I have updated the docs with commit cc33d29 in the 6.4 repo and ac3d55f in the 6.5 repo to point to the apache downloads to retrieve the latest version of FileVault. These changes have been published and are now live.

**Comment by tarekahf** [comment]
I am installing VaultClipse plugin and it needs filevault "2.4.34" as per my research. I am searching everywhere, and I cannot find it. When I try to setup the vault directory in FileVault Eclipse Plugin, I get the error "Please correct the vault directory".

Please help.

Tarek
