### ISSUE TITLE
Configuring Imaging Transcoding Library is incorrect and misleading 

### ISSUE THREAD

**Issue by leoberliant** [AdobeDocs/experience-manager-64.en#36]
Issue in help/assets/imaging-transcoding-library.md
Configuring Imaging Transcoding Library section of the KB is incorrect. It should be edited to:
[Imaging Transcoding Library.pdf](https://github.com/AdobeDocs/experience-manager-64.en/files/4040724/Imaging.Transcoding.Library.pdf)

Logged by Support

**Comment by ashishguptaiitb** [comment]
@leoberliant , then would this be the case with the [6.5 help article](https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/imaging-transcoding-library.html#configuring-imaging-transcoding-library) as well?

**Comment by leoberliant** [comment]
Yes, it's the same for 6.3, 6.4 and 6.5

**Comment by ashishguptaiitb** [comment]
Thanks for sharing the detailed info @leoberliant . This issue is addressed and the article is published live with the new info. I'm closing this issue.
