### ISSUE TITLE
Wrong subpackage name in the release notes

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-64.en#42]
Issue in help/release-notes/sp-release-notes.md

Link : https://docs.adobe.com/content/help/en/experience-manager-64/release-notes/assets/6.4.7.0_content_packages.txt

In the above link, one of the package has the wrong name.
It is listed in the documentation as "aem-bundle-remover-content 1.0.0" whereas the name of the package is "cq-bundle-remover-content"

**Comment by anujkapo** [comment]
Hi @vdhaliwa, Thanks for reporting the issue. I'll follow-up on this and get this rectified.

**Comment by anujkapo** [comment]
@vdhaliwa: The issue has been resolved. The Content Packages link in the Release Notes now points to a new file which has the correct version of the package:
https://docs.adobe.com/content/help/en/experience-manager-64/release-notes/assets/sp_6.4.7.0_content_packages.txt
