### ISSUE TITLE
404 link at the CSRF page

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-64.en#52]
Issue in help/sites-developing/csrf-protection.md

The "Cross-Site Request Forgery OWASP page ." link at the end of the page is going to 404

[1] https://owasp.org/www-community/crsf

**Comment by bohnertchris** [comment]
Thank you, @jbrarAdobe . We'll get this fixed.

**Comment by bohnertchris** [comment]
Fixed with commits:

0b491cb in 6.4 docs
89a5c11 in 6.5 docs
