### ISSUE TITLE
Web console link is broken

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-64.en#53]
Issue in help/sites-developing/the-basics.md

The link to "Web console" redirects to https://docs.adobe.com/content/help/en/experience-manager-64/developing/sites-deploying/configuring-web-console.md which throws 404.

The correct link should be https://docs.adobe.com/content/help/en/experience-manager-64/deploying/configuring/web-console.html

**Comment by bohnertchris** [comment]
Thank you for reporting this, @vdhaliwa. This was fixed with commit 6565fd4.
