### ISSUE TITLE
Classic UI image reference should be updated to Touch UI image reference

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-64.en#54]
Issue in help/sites-developing/workflows-models.md

See section "Make workflow models available in Touch UI" , step 6 image to be updated

Attached replacement image
![workflow_model_edit_activation2](https://user-images.githubusercontent.com/59840689/74492436-b99d5680-4e83-11ea-9ade-f3b81510539e.png)

Please update doc 6.5 also

{{Logged by Support}}

**Comment by lha-adobe** [comment]
Also, in the same "Make workflow models available in Touch UI" section , step 5 should be
In the Workflow editor, open **Page Information** menu option.  Click **Open Properties**.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @lha-adobe . We will look into it.

**Comment by aheim0** [comment]
Thank you for highlighting this issue and suggesting a solution. This has been addressed, and the changes are now live (for both 6.4 and 6.5).
