### ISSUE TITLE
MSM Rollout Configurations Path

### ISSUE THREAD

**Issue by jdpitt13** [AdobeDocs/experience-manager-64.en#56]
Issue in help/sites-developing/extending-msm.md

Under the heading Create the Rollout Configuration, there is a path in Tools to Rollout Configurations in step 2: Tools > MSM > Rollout Configurations.

This location does not exist and needs to be updated or these steps need to be removed if they are no longer valid in 6.4

**Comment by bohnertchris** [comment]
Thank you for the feedback, @jdpitt13 . We will have a look. CQDOC-15591

**Comment by aheim0** [comment]
This procedure been updated, and the changes are now live (for both 6.4 and 6.5).
