### ISSUE TITLE
What exactly is `<tenant>` in the described URL for the diagnostics page?

### ISSUE THREAD

**Issue by yashsway** [AdobeDocs/experience-manager-64.en#58]
Issue in help/sites-developing/ch-diagnostics.md

**Comment by bohnertchris** [comment]
Hello @yashsway . In a multitenant environment you would have multiple brands/identities within one AEM instance. For example

```
http://localhost:4502/conf/branda/settings/cloudsettings/default/contexthub.diagnostics.html
http://localhost:4502/conf/brandb/settings/cloudsettings/default/contexthub.diagnostics.html
```
If you are in a single tenant situation it would generally simply be

`http://localhost:4502/conf/mycompany/settings/cloudsettings/default/contexthub.diagnostics.html`

**Comment by bohnertchris** [comment]
Hello, @yashsway . I hope that my comment was helpful. If you do not have any more questions about this documentation, I will close this issue.

**Comment by bohnertchris** [comment]
Closing issue. Please create a new one if you find any issues with the documentation.
