### ISSUE TITLE
Troubleshooting for the Diagnostics Page

### ISSUE THREAD

**Issue by yashsway** [AdobeDocs/experience-manager-64.en#59]
Issue in help/sites-developing/ch-diagnostics.md

What if the diagnostics page gives you a 404: not found error? What steps can you take to debug and fix this error? I'm facing this exact issue right now, and there's no help anywhere on how to actually get this page to work.

**Comment by bohnertchris** [comment]
Hello @yashsway . Please be sure that you have enabled ContextHub Diagnostics as detailed in the document linked to from that page.

https://docs.adobe.com/content/help/en/experience-manager-64/administering/personalization/contexthub-config.html#debugging-contexthub

If you still need help, please reach out to our support team as they are there to address how-to and implementation issues.
