### ISSUE TITLE
See Versioning in AEM Assets doesn't have any link to take the user to that section/page

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-64.en#60]
Issue in help/assets/assets.md

The text  ** See Versioning in AEM Assets** doesn't have any corresponding link to take the user to that section/page in https://docs.adobe.com/content/help/en/experience-manager-64/assets/assets.html

[Logged by AEM Core Support]

**Comment by ashishguptaiitb** [comment]
Thanks for sharing this miss @sukohli . I am fixing it for both, AEM 6.4 and AEM 6.5 article.

**Comment by bohnertchris** [comment]
CQDOC-15664

**Comment by ashishguptaiitb** [comment]
@sukohli  the docs are updated with this fix. Thanks for sharing.
