### ISSUE TITLE
Searching for image rendition based on the input size (width, height) via QueryBuilder API.

### ISSUE THREAD

**Issue by RobertoPrimo** [AdobeDocs/experience-manager-64.en#61]
Hi,

I am wondering how is it possible to in just a single call to the QueryBuilder API retrieve the image rendition based on the specified size?

In the documentation for the QueryBuilder API a size predicate is mentioned (as can be seen in the image below) but I simply cannot find a way how to use it.
Could you please give an example of how the image size predicate is to be used with QueryBuilder API?
![image](https://user-images.githubusercontent.com/62694220/77824031-aecf1600-70ff-11ea-94c7-52ae4b96bdbf.png)

**Comment by sarchiz** [comment]
Thanks for logging this, @RobertoPrimo. We'll look into it and get back to you with an answer.

**Comment by sarchiz** [comment]
Quick update on this @RobertoPrimo .

We're no longer supporting the size predicate. We've removed that from the documentation.

For your specific use case, image renditions should have metadata in a subnode -  `jcr:content/metadata` with `tiff:ImageWidth` and `tiff:ImageLength` for width and height in pixels that can be queried like any other JCR property using the "property" predicate. See example below:

```
"cq5dam.thumbnail.48.48.png": {
        "jcr:created": "Wed Mar 25 2020 17:45:29 GMT+0000",
        "jcr:createdBy": "dam-writer-service",
        "jcr:primaryType": "nt:file",
        "jcr:content": {
          "jcr:lastModifiedBy": "dam-writer-service",
          "jcr:mimeType": "image/png",
          "jcr:mixinTypes": [
            "dam:Metadata"
          ],
          ":jcr:data": 3860,
          "jcr:lastModified": "Wed Mar 25 2020 17:45:29 GMT+0000",
          "jcr:primaryType": "oak:Resource",
          "metadata": {
            "dam:size": 3860,
            "dam:sha1": "eb22504387aeec1b13a4f34ab17e25bf073207d7",
            "tiff:ImageLength": 36,
            "jcr:primaryType": "nt:unstructured",
            "tiff:ImageWidth": 48,
            "dam:processingId": "vEPtNib2u2cfSrGM5rapZhjATjMdGntA"
          }
        }
      }
```

**Comment by sarchiz** [comment]
Closing this issue as resolved.

**Comment by RobertoPrimo** [comment]
Hi,

Thank you very much for answering my question....However, are you sure that every rendition contains the tiff:ImageLength attribute, since I cannot find it in my CRXDE as you can see on the attached screenshot....

![image](https://user-images.githubusercontent.com/62694220/80588730-27840380-8a19-11ea-91df-aca46a1d9427.png)
