### ISSUE TITLE
Loss of context - RTE Find and Replace plugin

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-64.en#63]
Issue in help/sites-administering/configure-rich-text-editor-plug-ins.md

The correct way to use find and replace as per RTE's design is that the text to be found and replaced should be entered at the same time, clicking on find and later entering the text to be replaced will reset the context of find and replace and append the text at the beginning of the sentence.

**Section to be modified** - https://docs.adobe.com/content/help/en/experience-manager-64/administering/operations/configure-rich-text-editor-plug-ins.html#understand--findreplace-plugin

Refer internal JIRA **CQ-4291369** for more information.

[Logged By support]

**Comment by bohnertchris** [comment]
Thanks for pointing out this detail, @BharathValse . We will have a look at the provided Jira.

**Comment by bohnertchris** [comment]
CQDOC-15711

**Comment by bohnertchris** [comment]
This was corrected with commit f899055 to this repo as well as commit c71b55c to the 6.5 repository.
