### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by svenux** [AdobeDocs/experience-manager-64.en#67]
Issue in help/forms/using/admin-help/files-back-recover.md

The link to https://articles.techrepublic.com.com/5100-1035_61-1043671.md (used in Text "See Backup Strategies and Backup and Restore") is not working and destination certificate is broken.

**Comment by singhkh** [comment]
Thanks, @svenux. I will take a look.

**Comment by anujkapo** [comment]
As per conversation with the engineering team, the broken link is removed from the docs. The updated 6.4 and 6.5 docs are available live:

- https://docs.adobe.com/content/help/en/experience-manager-64/forms/administrator-help/aem-forms-backup-recovery/files-back-recover.html
- https://docs.adobe.com/content/help/en/experience-manager-65/forms/administrator-help/aem-forms-backup-recovery/files-back-recover.html
