### ISSUE TITLE
Workflow spelling mistake ("worklow")

### ISSUE THREAD

**Issue by btl614** [AdobeDocs/experience-manager-64.en#69]
In the example, workflow is spelled as "worklow".

**Comment by bohnertchris** [comment]
Hello @btl614 . Thanks for reporting the problem, but to what page are you referring? Which example?

**Comment by bohnertchris** [comment]
CQDOC-16136

**Comment by bohnertchris** [comment]
Doing a search across the entire repo for "worklow" I corrected all occurrences.

This was corrected in commit d1222b7 to the 6.4 repository (this repo) and commit 104fa70 to the 6.5 repository.
