### ISSUE TITLE
Configuration in the replication agent for Brand Portal

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-64.en#72]
Issue in help/assets/configure-aem-assets-with-brand-portal.md

As per https://jira.corp.adobe.com/browse/CQ-4273689?focusedCommentId=18159223&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18159223 the checkbox "Close connection" needs to be ticked in the "Extended" tab of replication agents for Brand Portal to avoid running in an issue where it takes long time for assets to be published. 

This information should be added in the troubleshooting section

[Logged by Support]

**Comment by vishabhguptaadobe** [comment]
In-progress with the task: CQDOC-16036
Will be fixed soon.

**Comment by vishabhguptaadobe** [comment]
Updated the configuration steps in:

Troubleshooting: https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/publish/troubleshoot-parallel-publishing.html

FAQs: https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/introduction/brand-portal-faqs.html

**Comment by vishabhguptaadobe** [comment]
Troubleshooting steps and links are updated in all the doc repositories:
1.  Brand Portal troubleshoot issues in connection timeout: https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/publish/troubleshoot-parallel-publishing.html#connection-timeout 
2. Brand Portal FAQs: https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/introduction/brand-portal-faqs.html 
3. AEM 6.5 Assets configuration with Brand Portal: https://docs.adobe.com/content/help/en/experience-manager-65/assets/brandportal/configure-aem-assets-with-brand-portal.html 
4. AEM 6.4 Assets configuration with Brand Portal: https://docs.adobe.com/content/help/en/experience-manager-64/assets/brandportal/configure-aem-assets-with-brand-portal.html 
5. AEM 6.3 Assets configuration with Brand Portal: https://helpx.adobe.com/experience-manager/6-3/assets/using/brand-portal-configuring-integration.html#Testconfiguration
