### ISSUE TITLE
Incomplete sentence in section "Locating the script"

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-64.en#73]
Issue in help/sites-developing/the-basics.md

In the section "Locating the script", the following sentence is incomplete.
**The type hierarchy of /x is # while for /y the hierarchy is [ c, a,**

It should be like this:
The type hierarchy of /x is [ c, b, a, <default>] while for /y the hierarchy is [ c, a, <default>] because /y has the sling:resourceSuperType property whereas /x does not and therefore its supertype is taken from its resource type.

**Comment by aheim0** [comment]
Thank you for pointing this out. It looks like another artifact of our content migration to the new platform. We will get this fixed.

**Comment by aheim0** [comment]
The sections have been updated and published. Thanks for your help.
