### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-64.en#86]
Issue in help/sites-administering/saml-2-0-authenticationhandler.md

URL under Note* (blue box) is broken :
Clicking '_**See a demonstration of AEM and SAML integration**_ .' leads to 404 page

![image](https://user-images.githubusercontent.com/62261083/83883414-70faf900-a711-11ea-9a66-925d374ca10d.png)

**Comment by bohnertchris** [comment]
Thank you for reporting, @aaksinghAdobe. We will fix.

CQDOC-16206

**Comment by bohnertchris** [comment]
This was corrected in merge 52bd231 in the 6.5 repo and in merge 0f8e883 in the 6.4 repo.
