### ISSUE TITLE
Missing information about enabling Day CQ DAM Event Recorder configuration in the docs

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-64.en#89]
Issue in help/assets/asset-reports.md

Issue in help/assets/asset-reports.md

The doc contain information about enabling Asset Download service to generate an Asset Downloaded report, but it doesn't mention about enabling the _Day CQ DAM Event Recorder_ service.
![image](https://user-images.githubusercontent.com/59624839/84681517-37d93a80-af02-11ea-9138-873c06b9bd1d.png)

We can add the Note section as follows:
Before you can generate an Asset Downloaded report, ensure that Day CQ DAM Event Recorder service and Asset Download event type are enabled. From the web console ( https://[aem_server]:[port]/system/console/configMgr ), open the _Day CQ DAM Event Recorder_ configuration, and select _Enables this service_ and _Asset Downloaded (DOWNLOADED)_ option in Event Types, if not already selected.
![image](https://user-images.githubusercontent.com/59624839/84681695-84bd1100-af02-11ea-995b-96e7980c1c8a.png)

[Logged by AEM Support]

**Comment by ashishguptaiitb** [comment]
Thanks @sukohli for sharing the info for 6.4 as well :) I shall update docs of both the AEM versions.

**Comment by bohnertchris** [comment]
CQDOC-16319

**Comment by ashishguptaiitb** [comment]
@sukohli  the article is now updated with the prerequisite. Thanks again for sharing this information.
