### ISSUE TITLE
Missing information regarding Software Distribution in AEM 6.4 docs

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-64.en#90]
Issue in help/sites-administering/package-manager.md

There's some missing information regarding Software Distribution in AEM 6.4 docs, that exists on AEM 6.5 docs.

For AEM 6.5:
https://docs.adobe.com/content/help/en/experience-manager-65/administering/contentmanagement/package-manager.html#software-distribution-beta

For AEM 6.4: There's no such information regarding Software Distribution in the doc here:
https://docs.adobe.com/content/help/en/experience-manager-64/administering/contentmanagement/package-manager.html

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
CQDOC-16321

**Comment by bohnertchris** [comment]
This has been corrected in 6.4 with commit 2846e87.
