### ISSUE TITLE
Missing information about Asset Download report related to folder containing assets

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-64.en#92]
Issue in help/assets/asset-reports.md

There's some missing information about Asset Download report related to folder containing assets.
Please include the following as a Note to this page:
_Assets that are selected individually and downloaded are visible in the assets downloaded report. However, if a folder/collection containing assets is downloaded, those assets are not displayed in the assets downloaded report._
Verified in JIRA# CQ-101995

This same information is provided in Step 3 of the doc here: https://chl-author-preview.corp.adobe.com/content/help/en/experience-manager/brand-portal/using/brand-portal-download-users.html
![image](https://user-images.githubusercontent.com/59624839/85180168-ba3e6300-b250-11ea-84f2-306ff51797b7.png)

[Logged by AEM Support]

**Comment by mgulati1** [comment]
Thanks for notifying us @sukohli, we will look into the issue.

**Comment by mgulati1** [comment]
A Jira ticket [CQDOC-16338](https://jira.corp.adobe.com/browse/CQDOC-16338) has been created to track this change.

**Comment by bohnertchris** [comment]
CQDOC-16345

**Comment by mgulati1** [comment]
Thanks @sukohli. A note has been added and the issue has been fixed through the commit https://git.corp.adobe.com/AdobeDocs/experience-manager-64.en/pull/932/commits/a5e9b38cd7ed7a513c2ca6b6c0c3b5d0830dfdab.
