### ISSUE TITLE
the document is referencing old paths

### ISSUE THREAD

**Issue by hamid-k50** [AdobeDocs/experience-manager-64.en#93]
Issue in help/sites-developing/ht-projects-maven.md

The following document is referencing the old paths under "How-To Add Paths to the content Module"
https://docs.adobe.com/content/help/en/experience-manager-64/developing/devtools/ht-projects-maven.html#how-to-add-paths-to-the-content-module

support-initiated

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @hamid-k50. We'll look into it.

CQDOC-16383

**Comment by bohnertchris** [comment]
Apologies for overlooking responding on this thread. This issue was fixed in commit da8a61b. The documentation now points to the AEM as a Cloud Service documentation for Maven projects, which is the best practices guide for 6.4 and 6.5 as well.
