### ISSUE TITLE
The NOTE around cq:inplaceEditing contradicts itself.

### ISSUE THREAD

**Issue by somarc** [AdobeDocs/experience-manager-64.en#94]
Issue in help/sites-developing/multiple-inplace-editors.md

The NOTE on this page : 
https://docs.adobe.com/content/help/en/experience-manager-64/administering/operations/rich-text-editor.html
Says --
Do not name the RTE configuration node as config . Otherwise, the RTE configurations take effect for only the administrators and not for the users in the group content-author .

Which is correct, if you name it 'config' only admins can see the RTE toolbar

This document says to name it 'config' -- which prevents anyone by an admin from seeing the toolbar on the RTE.
Which is the source of a c14e ticket E-000166203

**Comment by jbrarAdobe** [comment]
[Logged By support]

**Comment by aheim0** [comment]
@somarc Thanks for raising this, we will investigate.

**Comment by ashishguptaiitb** [comment]
Hi @somarc , thanks for sharing this issue. I've updated the help article for 6.4 and also for 6.5. Those now contain an appropriate note in line with what we have in the RTE config article.
