### ISSUE TITLE
Doc Bug in release notes

### ISSUE THREAD

**Issue by vanegi** [AdobeDocs/experience-manager-64.en#96]
Issue in help/release-notes/sp-release-notes.md

It is highlighted that "Updated the jQuery version bundled in ContextHub to 3.4.1". But as part of GRANITE-19902 | NPR-28397, the jQuery version is updated to 3.2.1. 

Verified under /libs/granite/contexthub/dependencies/jquery and the correct version is updated to 3.2.1.

**Comment by anujkapo** [comment]
Thanks, @vanegi  for reporting the issue. We'll look into it.

**Comment by aheim0** [comment]
CQDOC-16405

**Comment by anujkapo** [comment]
The issue is fixed with the following git commit:
https://git.corp.adobe.com/AdobeDocs/experience-manager-64.en/pull/944/commits/98d52be43b1668b0f16ae18fc82402acc1058a38
