### ISSUE TITLE
Duplicate MBean URLs in Security Health Check section of this doc

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-64.en#98]
Issue in help/sites-administering/operations-dashboard.md

There's a duplicate value of the MBean for Security Health Check in the document here:
https://docs.adobe.com/content/help/en/experience-manager-64/administering/operations/operations-dashboard.html#health-checks-provided-with-aem
![image](https://user-images.githubusercontent.com/59624839/87073691-d009cd00-c1eb-11ea-9d67-a5bd4ff0b867.png)

There should be just one URL for that Health Check's MBean. It can be found here on AEM: /system/console/jmx/org.apache.sling.healthcheck%3Aname%3Dsecuritychecks%2Ctype%3DHealthCheck

![image](https://user-images.githubusercontent.com/59624839/87073718-da2bcb80-c1eb-11ea-809b-1b5c96f3460e.png)

[Logged by AEM Support]

**Comment by anujkapo** [comment]
Thanks for reporting the issue, @sukohli. We will fix it.

**Comment by anujkapo** [comment]
Tracked via CQDOC-16439.

**Comment by raimanS** [comment]
Link fixed [1].
[1] - https://experienceleague.adobe.com/docs/experience-manager-64/administering/operations/operations-dashboard.html#health-checks-provided-with-aem
