### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by yetanotherbhai** [AdobeDocs/experience-manager-64.en#99]
Issue in help/sites-administering/aem-livefyre-recipes.md

Below links under https://docs.adobe.com/content/help/en/experience-manager-64/administering/integration/aem-livefyre-recipes.html#use-livefyre-aem-assets-integration-to-import-ugc-in-aem-assets
Getting Started
Configure AEM to use Livefyre
Import UGC curated by Livefyre in to AEM Assets

For ex - one of the url says https://https//helpx.adobe.com/experience-manager/6-3/sites/administering/using/livefyre.html#UseLivefyrewithAEMAssets
Notice double https

**Comment by aheim0** [comment]
@yetanotherbhai Thanks for highlighting this, we will investigate.

**Comment by aheim0** [comment]
Tracking with CQDOC-16443.

**Comment by aheim0** [comment]
@yetanotherbhai 
We have corrected these, and a few other, links. The updated pages will be published soon.
Will close this issue now.
